apiVersion: apps/v1
kind: Deployment
metadata:
  name: excalidraw-client
  labels:
    app: excalidraw
    component: client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: excalidraw
      component: client
  template:
    metadata:
      labels:
        app: excalidraw
        component: client
    spec:
      containers:
      - name: excalidraw-client
        image: excalidraw-client:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
