apiVersion: apps/v1
kind: Deployment
metadata:
  name: excalidraw-server
  labels:
    app: excalidraw
    component: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: excalidraw
      component: server
  template:
    metadata:
      labels:
        app: excalidraw
        component: server
    spec:
      containers:
      - name: excalidraw-server
        image: ghcr.io/kitsteam/excalidraw-storage-backend:main
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: PORT
          value: "8080"
        - name: LOG_LEVEL
          value: "log"
        command: ["npm", "run", "start:prod"]  # Skip entrypoint.sh
        volumeMounts:
        - name: excalidraw-storage
          mountPath: /data
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /api/v2/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/v2/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: excalidraw-storage
        persistentVolumeClaim:
          claimName: excalidraw-storage-pvc
