apiVersion: v1
kind: Service
metadata:
  name: excalidraw-server
  labels:
    app: excalidraw
    component: server
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: excalidraw
    component: server
