apiVersion: v1
kind: Service
metadata:
  name: excalidraw-server
  labels:
    app: excalidraw
    component: server
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: excalidraw
    component: server
