apiVersion: v1
kind: ConfigMap
metadata:
  name: excalidraw-config
  labels:
    app: excalidraw
data:
  # Client configuration
  VITE_APP_WS_SERVER_URL: "wss://excalidraw.json-server.win/socket"
  VITE_APP_HTTP_STORAGE_BACKEND_URL: "https://excalidraw.json-server.win/files"
  
  # Server configuration
  STORAGE_PATH: "/data/excalidraw"
