apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: excalidraw-storage-pvc
  labels:
    app: excalidraw
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
